s = input().split(' ')
ax = int(s[0])
ay = int(s[1])
s = input().split(' ')
bx = int(s[0])
by = int(s[1])
s = input().split(' ')
cx = int(s[0])
cy = int(s[1])
print(str((ax + bx + cx) / 3) + ' ' + str((ay + by + cy) / 3))
